SELECT * FROM Sales

--Revenue generated by different product categories per country--
SELECT Country,Product_Category, SUM(Revenue) AS Revenue
FROM Sales
GROUP BY Country, Product_Category
ORDER BY Country

--Total sales by category--
SELECT COUNT(Order_Quantity) AS Total_Sale_By_Category, Product_Category FROM Sales
GROUP BY Product_Category

--Total sales by sub category--
SELECT COUNT(Order_Quantity) AS Total_Sale_By_Sub_Category, Sub_Category FROM Sales
GROUP BY Sub_Category
ORDER BY Total_Sale_By_Sub_Category

--Total sales by gender--
SELECT Customer_Gender, COUNT(Order_Quantity) AS Total_Sale_By_Gender, (COUNT(*)*100.0/(SELECT COUNT(*) FROM Sales)) AS Percentage_Sales_By_Gender 
FROM Sales
GROUP BY Customer_Gender

--Best month of the year for product sales--
SELECT COUNT(Order_Quantity) AS Total_Sale_By_Month, [Month] FROM Sales
GROUP BY [Month]
ORDER BY Total_Sale_By_Month

--Which country bought the most product in total--
SELECT COUNT(Order_Quantity) AS Total_Sales_By_Country, Country FROM Sales
GROUP BY Country
ORDER BY Total_Sales_By_Country

--Which country bought the most bikes in total--
SELECT COUNT(CASE WHEN Product_Category = 'Bikes' THEN 1 END) AS Total_Bike_Sales_By_Country, Country FROM Sales
GROUP BY Country
ORDER BY Total_Bike_Sales_By_Country

SELECT COUNT(Order_Quantity) AS Total_Bike_Sales_By_Country, Country FROM Sales
WHERE Product_Category = 'Bikes'
GROUP BY Country
ORDER BY Total_Bike_Sales_By_Country

--Which country sales generate the most revenue--
SELECT SUM(Revenue) AS Total_Revenue, Country FROM Sales
GROUP BY Country
ORDER BY Total_Revenue

--Customer Age Group--
Select COUNT(Order_Quantity) AS Total_Sales_By_Age, Age_Group From Sales
GROUP BY Age_Group
ORDER BY Total_Sales_By_Age